import type { Product } from "./types"
import mele from "../images/mele.jpg"

export const products: Product[] = [
  {
    id: "1",
    name: "Mele Rosse",
    price: 2.5,
    unit: "kg",
    image: mele,
    category: "Frutta",
  },
  {
    id: "2",
    name: "Banane",
    price: 1.8,
    unit: "kg",
    image: "/public/images/banana.jpg",
    category: "Frutta",
  },
  {
    id: "3",
    name: "Arance Navel",
    price: 2.2,
    unit: "kg",
    image: "/public/images/arance.jpg",
    category: "Frutta",
  },
  {
    id: "4",
    name: "Lattuga Romana",
    price: 1.2,
    unit: "pezzo",
    image: "/public/images/lattuga.jpg",
    category: "Verdura",
  },
  {
    id: "5",
    name: "Pomodori Ciliegino",
    price: 3.0,
    unit: "kg",
    image: "/public/images/pomodori.jpg",
    category: "Verdura",
  },
  {
    id: "6",
    name: "Zucchine",
    price: 1.9,
    unit: "kg",
    image: "/public/images/zucchine.jpg",
    category: "Verdura",
  },
  {
    id: "7",
    name: "Biscotti al Cioccolato",
    price: 2.99,
    unit: "confezione",
    image: "/public/images/biscotto.jpg",
    category: "Biscotti",
  },
  {
    id: "8",
    name: "Frollini Classici",
    price: 1.85,
    unit: "confezione",
    image: "/public/images/frollini.jpg",
    category: "Biscotti",
  },
  {
    id: "9",
    name: "Latte Fresco Intero",
    price: 1.1,
    unit: "litro",
    image: "/public/images/latte.jpg",
    category: "Latte",
  },
  {
    id: "10",
    name: "Latte Parzialmente Scremato UHT",
    price: 0.95,
    unit: "litro",
    image: "/public/images/latteP.jpg",
    category: "Latte",
  },
  {
    id: "11",
    name: "Shampoo Delicato",
    price: 4.5,
    unit: "flacone",
    image: "/public/images/shampoo.jpg",
    category: "Cura Personale",
  },
  {
    id: "12",
    name: "Dentifricio Menta Fresca",
    price: 2.75,
    unit: "tubetto",
    image: "/public/images/dentifricio.jpg",
    category: "Cura Personale",
  },
  {
    id: "13",
    name: "Acqua Naturale",
    price: 0.5,
    unit: "bottiglia",
    image: "/public/images/acqua.jpg",
    category: "Bibite",
  },
  {
    id: "14",
    name: "Coca-Cola",
    price: 1.5,
    unit: "lattina",
    image: "/public/images/cocacola.jpg",
    category: "Bibite",
  },
  {
    id: "15",
    name: "Succo d'Arancia",
    price: 1.99,
    unit: "litro",
    image: "/public/images/succo.jpg",
    category: "Bibite",
  },
  {
    id: "16",
    name: "Birra Artigianale IPA",
    price: 3.8,
    unit: "bottiglia",
    image: "/public/images/birraA.jpg",
    category: "Birre",
  },
  {
    id: "17",
    name: "Birra Lager Classica",
    price: 1.2,
    unit: "bottiglia",
    image: "/public/images/birra.jpg",
    category: "Birre",
  },
  {
    id: "18",
    name: "Vino Rosso Chianti",
    price: 8.99,
    unit: "bottiglia",
    image: "/public/images/vinoRosso.jpg",
    category: "Vino",
  },
  {
    id: "19",
    name: "Vino Bianco Vermentino",
    price: 7.5,
    unit: "bottiglia",
    image: "/public/images/vinoBianco.jpg",
    category: "Vino",
  },
  {
    id: "20",
    name: "Pane Casereccio",
    price: 3.2,
    unit: "pezzo",
    image: "/public/images/pane.jpg",
    category: "Panetteria",
  },
  {
    id: "21",
    name: "Cornetti Vuoti",
    price: 0.8,
    unit: "pezzo",
    image: "/public/images/cornetti.jpg",
    category: "Panetteria",
  },
  {
    id: "22",
    name: "Formaggio Parmigiano",
    price: 12.0,
    unit: "kg",
    image: "/public/images/formaggio.jpg",
    category: "Latticini",
  },
  {
    id: "23",
    name: "Mozzarella di Bufala",
    price: 3.5,
    unit: "confezione",
    image: "/public/images/mozzarella.jpg",
    category: "Latticini",
  },
  {
    id: "24",
    name: "Salmone Fresco",
    price: 18.5,
    unit: "kg",
    image: "/public/images/salmone.jpg",
    category: "Pesce",
  },
  {
    id: "25",
    name: "Gamberi Sgusciati",
    price: 15.0,
    unit: "confezione",
    image: "/public/images/gambero.jpg",
    category: "Pesce",
  },
  {
    id: "26",
    name: "Petto di Pollo",
    price: 9.5,
    unit: "kg",
    image: "/public/images/pettoPollo.jpg",
    category: "Carne",
  },
  {
    id: "27",
    name: "Salsiccia Fresca",
    price: 7.0,
    unit: "kg",
    image: "/public/images/salsiccia.jpg",
    category: "Carne",
  },
  {
    id: "28",
    name: "Pasta di Grano Duro",
    price: 0.9,
    unit: "confezione",
    image: "/public/images/pasta.jpg",
    category: "Dispensa",
  },
  {
    id: "29",
    name: "Olio Extra Vergine d'Oliva",
    price: 6.5,
    unit: "litro",
    image: "/public/images/olio.jpg",
    category: "Dispensa",
  },
  {
    id: "30",
    name: "Detersivo Lavatrice",
    price: 5.99,
    unit: "flacone",
    image: "/public/images/detersivo.jpg",
    category: "Pulizia Casa",
  },
]

export const categories: string[] = [
  "Tutte le Categorie",
  "Frutta",
  "Verdura",
  "Biscotti",
  "Latte",
  "Cura Personale",
  "Bibite",
  "Birre",
  "Vino",
  "Panetteria",
  "Latticini",
  "Pesce",
  "Carne",
  "Dispensa",
  "Pulizia Casa",
]
